<a href="https://colab.research.google.com/github/yashagarwal6/data_science-/blob/main/pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
dct = {
    'name' : ['Tom','Nick','Krish','Jack'],
    'age' : [20,21,19,18],
    'roll' : [1,2,3,4]
}
#complete structure is dataframe
#display function is used to print datadframes instead of print


df=pd.DataFrame(dct, index = ['A','B','C','D']) #WE CAN EDIT index
display(df)

    name  age  roll
A    Tom   20     1
B   Nick   21     2
C  Krish   19     3
D   Jack   18     4

In [31]:
df = pd.read_csv('student_data.csv')#file path
# df.tail(3) #from last just like head
# df.shape #provides the shape of data , columns and rows
#metadata is the data of data
# df.info()
# df.describe() #statistical summary
# df['internet_usage'] #for particular column
# df[['study_hours','internet_usage']]

# df.iloc[0: 5] #5 is no. of rows
# df.loc[df['study_hours']==11],['study_hours']
# df.loc[df['study_hours']==11,['study_hours','sleep_hours']]
df.loc[df['study_hours']==11,['study_hours','sleep_hours']].iloc[4: 8] #with range

(      study_hours  attendance  sleep_hours  internet_usage  \
 2              11          60            7               6
 9              11          77            4               9
 10             11          64            8               8
 29             11          63            9              10
 30             11          45            5               2
 ...           ...         ...          ...             ...
 9969           11          84            8               2
 9971           11          81            9               6
 9978           11          92            8               2
 9979           11          78            9               5
 9988           11          94            6               9

       assignments_completed  previous_score  exam_score placement_status
 2                        10              45      100.00           Placed
 9                        15              69      100.00           Placed
 10                       12              76      100.00           Placed
 29                        1              72       96.59           Placed
 30                        4              93      100.00           Placed
 ...                     ...             ...         ...              ...
 9969                      3              83      100.00           Placed
 9971                      0              85      100.00           Placed
 9978                     16              79      100.00           Placed
 9979                     18              82      100.00           Placed
 9988                      6              67      100.00           Placed

 [868 rows x 8 columns],
 ['study_hours'])

In [49]:
df = pd.read_csv('student_data.csv')
# df.loc[df['assignments_completed']==8].iloc[1]
# df[df["assignments_completed"] > 3]
df.rename(columns = {'assignments_completed': 'assign_completed'},inplace = True)
df.dropna()

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [57]:
import pandas as pd
dct = {'name' : ['Tom','Nick','Krish','Jack'],
    'age' : [20,None,19,18],
    'roll' : [1,2,3,None]
}
df=pd.DataFrame(dct)
df.dropna()

    name   age  roll
0    Tom  20.0   1.0
2  Krish  19.0   3.0